### ISSUE TITLE
Embedded and External Styling

### ISSUE THREAD

**Issue by mlovse1** [tonylee1556/Vido-VideoConferencing#11]
You have nearly identical, if not, identical embedded styling for the body on many of your pages. To make your code cleaner, you could move that to your external sheet and eliminate it on each of your other pages. 
![stylesheet](https://user-images.githubusercontent.com/67603844/114326210-4af47100-9af9-11eb-99d7-faad6bd552c7.jpg)

**Comment by tonylee1556** [comment]
Thank you for reviewing my code, I have moved all the embedded CSS into an external file.
